CLASSPATH = ../../../ij.jar
EXT = .java
SRC = MSA_514.java 
DEST = ..

all:
	@echo -n "Compilation...."
	@javac -classpath $(CLASSPATH) -d $(DEST) $(SRC)
	@echo "[OK]"
clean:
	@echo -n "Make clean..."
	@rm -f ../*.class
	@echo "[OK]"
